Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
    vb.cpus = 1
  end
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "provision/playbook.yml"
  # end
end
