---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Iniciar serviço Nginx
  service:
    name: nginx
    state: started
  become: yes

- name: Habilitar serviço Nginx na inicialização
  service:
    name: nginx
    enabled: yes
  become: yes
