version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: FrontEndDockerFile
    ports:
      - '3000:80'
  backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    ports:
      - '5000:5000'
